name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright dependencies (Core)
        run: npx playwright install-deps
        working-directory: ./packages/core

      - name: Install Playwright browsers (Core)
        run: npx playwright install
        working-directory: ./packages/core

      - name: Install VS Code test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Lint all packages
        run: npm run lint

      - name: Type check all packages
        run: npm run typecheck

      - name: Build all packages
        run: npm run build

      - name: Test core package
        run: npm run test:core
