name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Cache Playwright system dependencies
      uses: actions/cache@v4
      id: playwright-deps-cache
      with:
        path: |
          /var/cache/apt
          /var/lib/apt/lists
        key: ${{ runner.os }}-playwright-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-deps-
    
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    
    - name: Install Playwright system dependencies
      if: steps.playwright-deps-cache.outputs.cache-hit != 'true'
      run: npx playwright install-deps
    
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install
    
    - name: Run linting
      run: npm run lint
    
    - name: Check formatting
      run: npm run format:check
    
    - name: Type check
      run: npm run typecheck
    
    - name: Cache build output
      uses: actions/cache@v4
      with:
        path: |
          dist
          .vite
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json', 'src/**/*', 'vite.config.ts') }}
        restore-keys: |
          ${{ runner.os }}-build-
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm run test